### ISSUE TITLE
Appimage does not show icon.

### ISSUE THREAD

**Issue by Abhinav1217** [showcheap/postman-appimage#3]
_Note: Since there is an updated version of postman since your last release, I am running your [raw build.sh](https://raw.githubusercontent.com/suciptoid/postman-appimage/master/build.sh) on my system directly._

I initially did not change anything in your script, since it always download the latest version of postman. After the build is completed, Generated Appimage does not show any icons even after executing it.  In contrast, my other appimages like motrix, krita, does show their icons. I even changed the `Icon=` line to point to png image directly, but it still doesn't show icon. 

![image](https://user-images.githubusercontent.com/740584/130609237-cd6e1fd9-3da0-4d05-af6b-014edcf9de71.png)

**Comment by suciptoid** [comment]
Hi, have you update to latest appimaged?

You can read here:
https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md

I've tested on my laptop using latest appimaged, and it's showing on app list and on file manager (nautilus)
![Screenshot from 2021-08-25 08-55-05](https://user-images.githubusercontent.com/1310895/130713539-ff12e23e-fafe-402e-aa40-7e52ef81a84e.png)
![Screenshot from 2021-08-25 08-54-54](https://user-images.githubusercontent.com/1310895/130713543-8e1c3bab-7218-44f9-ab1d-22081f37c77d.png)

**Comment by Abhinav1217** [comment]
I will try that, Currently my appimages are managed by [AppimageLauncher ](https://github.com/TheAssassin/AppImageLauncher).  Last I checked, go-appimage was still experimental.

**Comment by suciptoid** [comment]
You can also check the latest build on https://github.com/suciptoid/postman-appimage/releases/tag/continous, I've to update the build script using Github action to make it always up to date.

And I will close this issue for now. Feel free to reopen if the issue persists with the latest appimaged.
